# Generated by Django 6.0.7 on 2026-07-13 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
    ]
